"""Fetch and validate the public USCIS H-1B cap-registration aggregates.

The USCIS source is an HTML table rather than a downloadable file. This script deliberately fails
closed if its headers, arithmetic, fiscal-year coverage, or the final rule's projected probabilities
change. Review any upstream change before committing regenerated src/lottery_data.js.
"""
from datetime import date
from html.parser import HTMLParser
from pathlib import Path
import json
import re
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "lottery_data.js"
USCIS_URL = ("https://www.uscis.gov/working-in-the-united-states/temporary-workers/"
             "h-1b-specialty-occupations/h-1b-electronic-registration-process")
RULE_URL = ("https://www.federalregister.gov/documents/full_text/text/2025/12/29/"
            "2025-23853.txt")
RULE_PAGE = ("https://www.federalregister.gov/documents/2025/12/29/2025-23853/"
             "weighted-selection-process-for-registrants-and-petitioners-seeking-to-file-cap-subject-h-1b")
EXPECTED_HEADERS = [
    "Cap Fiscal Year", "Total Registrations", "Eligible Registrations*",
    "Eligible Registrations for Beneficiaries with No Other Eligible Registrations",
    "Eligible Registrations for Beneficiaries with Multiple Eligible Registrations",
    "Selected Registrations",
]
SYSTEM = {2021: "registration-centric", 2022: "registration-centric",
          2023: "registration-centric", 2024: "registration-centric",
          2025: "beneficiary-centric", 2026: "beneficiary-centric"}


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "H1B-Sponsor-Explorer/1.0"})
    with urllib.request.urlopen(req, timeout=60) as response:
        return response.read().decode("utf-8", "replace")


class Tables(HTMLParser):
    def __init__(self):
        super().__init__()
        self.tables, self.table, self.row, self.cell = [], None, None, None

    def handle_starttag(self, tag, attrs):
        if tag == "table": self.table = []
        elif self.table is not None and tag == "tr": self.row = []
        elif self.row is not None and tag in ("th", "td"): self.cell = []

    def handle_data(self, data):
        if self.cell is not None: self.cell.append(data)

    def handle_endtag(self, tag):
        if tag in ("th", "td") and self.cell is not None:
            self.row.append(" ".join("".join(self.cell).split()))
            self.cell = None
        elif tag == "tr" and self.row is not None:
            if self.row: self.table.append(self.row)
            self.row = None
        elif tag == "table" and self.table is not None:
            self.tables.append(self.table)
            self.table = None


def registration_history(page):
    parser = Tables(); parser.feed(page)
    table = next((t for t in parser.tables if t and t[0] == EXPECTED_HEADERS), None)
    if table is None:
        raise ValueError("USCIS historical table headers changed; refusing to guess")
    rows = []
    for raw in table[1:]:
        if len(raw) != 6: raise ValueError(f"unexpected USCIS row: {raw}")
        nums = [int(x.replace(",", "")) for x in raw]
        fy, total, eligible, single, multiple, selected = nums
        if fy not in SYSTEM: continue
        if single + multiple != eligible:
            raise ValueError(f"FY{fy}: eligible registration categories do not reconcile")
        if not 0 <= selected <= eligible <= total:
            raise ValueError(f"FY{fy}: registration totals have an invalid ordering")
        rows.append(dict(fy=fy, total=total, eligible=eligible, single=single,
                         multiple=multiple, selected=selected, system=SYSTEM[fy]))
    if [r["fy"] for r in rows] != list(SYSTEM):
        raise ValueError("expected complete FY2021-FY2026 USCIS history")
    return rows


def projected_weights(rule):
    clean = rule.replace("\x00", "")
    match = re.search(
        r"15\.29 percent for\s+level I, 30\.58 percent for level II, "
        r"45\.87 percent for level III, and\s+61\.16 percent for level IV", clean)
    if not match:
        raise ValueError("DHS projected probabilities changed or could not be verified")
    return [
        dict(level="I", weight=1, projected=15.29, label="entry"),
        dict(level="II", weight=2, projected=30.58, label="qualified"),
        dict(level="III", weight=3, projected=45.87, label="experienced"),
        dict(level="IV", weight=4, projected=61.16, label="expert"),
    ]


def main():
    data = dict(asOf=date.today().strftime("%B %-d, %Y"), source=USCIS_URL,
                rule=RULE_PAGE, history=registration_history(fetch(USCIS_URL)),
                weights=projected_weights(fetch(RULE_URL)))
    body = "// Generated by pipeline/fetch_lottery.py; do not edit by hand.\n"
    body += "const LOTTERY=" + json.dumps(data, separators=(",", ":")) + ";\n"
    OUT.write_text(body)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(data['history'])} years, {len(data['weights'])} wage levels")


if __name__ == "__main__":
    main()
